### ISSUE TITLE
setLeftSelection and setRightSelection not working as expected

### ISSUE THREAD

**Issue by siddharthKarnik** [dolphinwang/RangeSeekbar#5]
I write a code something like this : `rangeFriday.setLeftSelection(listTimesOriginal.indexOf(timeSplit[1]));
                rangeFriday.setRightSelection(listTimesOriginal.indexOf(timeSplit[2]));` 
I have debugged the code and the proper integer value is going in but the left and right cursors both move to the start of the range bar.
I think this variable `mPartLength` in the functions `setLeftSelection(int partIndex)` and `setRightSelection(int partIndex)` is creating issues. Cant understand what to do with it....

Kindly modify the code to get it working or guide me to the solution..
The library is good and really usefull except this one feature...

**Comment by zwl-git** [comment]
To reset  mPartLength. 
 mSeekbar.setLeftSelection(mLeftSelection,partLength)
 public void setLeftSelection(int partIndex, int partLength) {
        mPartLength = partLength;
        ...
}

**Comment by dolphinwang** [comment]
Oh, I just test this issue. @siddharthKarnik I think you may call setLeftSelection/setRightSelection before view has been measured. Now this issue has been fixed. You can pull the newest code.
